//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GRASPEntities : DbContext
{
    public GRASPEntities()
        : base("name=GRASPEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Contact> Contact { get; set; }
    public DbSet<DataTransfer> DataTransfer { get; set; }
    public DbSet<Email> Email { get; set; }
    public DbSet<EmailAccount> EmailAccount { get; set; }
    public DbSet<Form> Form { get; set; }
    public DbSet<FormResponse> FormResponse { get; set; }
    public DbSet<FormResponseCoords_ResponseValue> FormResponseCoords_ResponseValue { get; set; }
    public DbSet<frontline_group> frontline_group { get; set; }
    public DbSet<FrontlineMultimediaMessagePart> FrontlineMultimediaMessagePart { get; set; }
    public DbSet<GroupMembership> GroupMembership { get; set; }
    public DbSet<Keyword> Keyword { get; set; }
    public DbSet<keywordaction> keywordaction { get; set; }
    public DbSet<message> message { get; set; }
    public DbSet<reminder> reminder { get; set; }
    public DbSet<ResponseValue> ResponseValue { get; set; }
    public DbSet<SmsInternetServiceSettingValue> SmsInternetServiceSettingValue { get; set; }
    public DbSet<StatisticsTable> StatisticsTable { get; set; }
    public DbSet<SurveyElement> SurveyElement { get; set; }
    public DbSet<FormResponseCoord> FormResponseCoords { get; set; }
    public DbSet<Report> Reports { get; set; }
    public DbSet<Role> Roles { get; set; }
    public DbSet<SmsInternetServiceSetting> SmsInternetServiceSettings { get; set; }
    public DbSet<SmsInternetServiceSettings_SmsInternetServiceSettingValue> SmsInternetServiceSettings_SmsInternetServiceSettingValue { get; set; }
    public DbSet<SmsModemSetting> SmsModemSettings { get; set; }
    public DbSet<FormFieldExport> FormFieldExport { get; set; }
    public DbSet<SurveyListAPI> SurveyListAPI { get; set; }
    public DbSet<ReportField> ReportFields { get; set; }
    public DbSet<User_Credential> User_Credential { get; set; }
    public DbSet<BindingRules> BindingRules { get; set; }
    public DbSet<BindingContainer> BindingContainer { get; set; }
    public DbSet<ConstraintContainer> ConstraintContainer { get; set; }
    public DbSet<FormField> FormField { get; set; }
    public DbSet<FormField_ConstraintContainer> FormField_ConstraintContainer { get; set; }
    public DbSet<FormField_FormFieldAndBinding> FormField_FormFieldAndBinding { get; set; }
    public DbSet<FormFieldAndBinding> FormFieldAndBinding { get; set; }
    public DbSet<Survey> Survey { get; set; }
    public DbSet<Survey_SurveyElement> Survey_SurveyElement { get; set; }
}
